DOCUMENT_HEADER = "SonarQube Vulnerability Tracker"
TABLE_HEADER_PROJECT_NAME = "Project Name"
TABLE_HEADER_ANALYSIS = "Analysis Date"
TABLE_HEADER_BRANCH = "Branch"
SUBHEADER_DOCUMENT = "List of Issues Detected"
TABLE_HEADER_SEVERITY = "Severity"
TABLE_HEADER_DESCRIPTION = "Description"
TABLE_HEADER_TYPE = "Type"
TABLE_HEADER_FILE_NAME = "File Name"
TABLE_HEADER_LINE_NUMBER = "Line No"
TABLE_HEADER_SUMMARY_BUGS = "Bugs"
TABLE_HEADER_SUMMARY_VULNERABILITIES = "Vulnerabilities"
TABLE_HEADER_SUMMARY_CODE_SMELLS = "Code Smells"
TABLE_HEADER_SUMMARY_DUPLICATION_PER = "Duplication Percentage"
TABLE_HEADER_REPORT_SUMMARY = "Report Summary"
CREATOR_CREDIT=f'RedCoffee : SonarQube reports made easy by <a href="https://github.com/Anubhav9" color="blue">Anubhav9</a>'
TABLE_HEADER_DUPLICATED_LINES="Number of Duplicated Lines"
SUBHEADER_DUPLICATION_DOCUMENT="Duplications Detected"
